// <auto-generated />
using System;
using LMS_Data_Access_Layer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS_Data_Access_Layer.Migrations
{
    [DbContext(typeof(LMS_CMS_Context))]
    [Migration("20251210113402_CreateAcademicYearAndSemester")]
    partial class CreateAcademicYearAndSemester
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.AcademicDegree", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("AcademicDegrees");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Building", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SchoolID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Department", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Floor", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("buildingID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("buildingID");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Grade", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("DateFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FRI")
                        .HasColumnType("int");

                    b.Property<int?>("MON")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SAT")
                        .HasColumnType("int");

                    b.Property<int?>("SUN")
                        .HasColumnType("int");

                    b.Property<long>("SectionID")
                        .HasColumnType("bigint");

                    b.Property<int?>("THRU")
                        .HasColumnType("int");

                    b.Property<int?>("TUS")
                        .HasColumnType("int");

                    b.Property<int?>("WED")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SectionID");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Job", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("JobCategoryID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("JobCategoryID");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.JobCategory", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("JobCategories");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.ReasonForLeavingWork", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("ReasonsForLeavingWork");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Section", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SchoolID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("SchoolID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Employee", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("AcademicDegreeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AnnualLeaveBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AttendanceTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthdayDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CanReceiveMessageFromParent")
                        .HasColumnType("bit");

                    b.Property<bool?>("CanReceiveRequest")
                        .HasColumnType("bit");

                    b.Property<bool?>("CanReceiveRequestFromParent")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CasualLeavesBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DateOfLeavingWork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("DelayAllowance")
                        .HasColumnType("real");

                    b.Property<long?>("DepartmentID")
                        .HasColumnType("bigint");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExpireDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("int");

                    b.Property<bool?>("HasAttendance")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsRestrictedForLoctaion")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("bit");

                    b.Property<long?>("JobID")
                        .HasColumnType("bigint");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MonthSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MonthlyLeaveRequestBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NationalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Nationality")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ReasonOfLeavingID")
                        .HasColumnType("bigint");

                    b.Property<string>("ResidenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Role_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ar_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("en_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("AcademicDegreeID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("JobID");

                    b.HasIndex("ReasonOfLeavingID");

                    b.HasIndex("Role_ID");

                    b.HasIndex("User_Name")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.AcademicYear", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("schoolId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("schoolId");

                    b.ToTable("AcademicYears");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.Classroom", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("AcademicYearID")
                        .HasColumnType("bigint");

                    b.Property<long>("FloorID")
                        .HasColumnType("bigint");

                    b.Property<long>("GradeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AcademicYearID");

                    b.HasIndex("FloorID");

                    b.HasIndex("GradeID");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.School", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CitySubdivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaximumPeriodCountRemedials")
                        .HasColumnType("int");

                    b.Property<int?>("MaximumPeriodCountTimeTable")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportHeaderOneAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportHeaderOneEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportHeaderTwoAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportHeaderTwoEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretNumber1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretNumber2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VatNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.Semester", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("AcademicYearID")
                        .HasColumnType("bigint");

                    b.Property<string>("DateFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("AcademicYearID");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.Student", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmergencyContactMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactRelation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardianRelation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsRegisteredInNoor")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("bit");

                    b.Property<string>("LandMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherExperiences")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherNationalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherNationalIDExpiredDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherPassportExpireDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherPassportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherProfession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherQualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherWorkPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalIDExpiredDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Nationality")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportExpiredDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickUpContactMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickUpContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickUpContactRelation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SchoolID")
                        .HasColumnType("bigint");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ar_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("en_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("SchoolID");

                    b.HasIndex("User_Name")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.Subject", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<float>("AssignmentCutOffDatePercentage")
                        .HasColumnType("real");

                    b.Property<double>("CreditHours")
                        .HasColumnType("float");

                    b.Property<long>("GradeID")
                        .HasColumnType("bigint");

                    b.Property<bool>("HideFromGradeReport")
                        .HasColumnType("bit");

                    b.Property<string>("IconLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfSessionPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("OrderInCertificate")
                        .HasColumnType("int");

                    b.Property<float>("PassByDegree")
                        .HasColumnType("real");

                    b.Property<string>("SubjectArabicNameInCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SubjectCategoryID")
                        .HasColumnType("bigint");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectEnglishNameInCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalMark")
                        .HasColumnType("real");

                    b.Property<string>("ar_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("en_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("GradeID");

                    b.HasIndex("SubjectCategoryID");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.SubjectCategory", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("SubjectCategory");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Role", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Building", b =>
                {
                    b.HasOne("LMS_Data_Access_Layer.Models.Learning_Management_System.School", "school")
                        .WithMany("Buildings")
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("school");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Floor", b =>
                {
                    b.HasOne("LMS_Data_Access_Layer.Models.Administration.Building", "building")
                        .WithMany("Floors")
                        .HasForeignKey("buildingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("building");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Grade", b =>
                {
                    b.HasOne("LMS_Data_Access_Layer.Models.Administration.Section", "Section")
                        .WithMany("Grades")
                        .HasForeignKey("SectionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Job", b =>
                {
                    b.HasOne("LMS_Data_Access_Layer.Models.Administration.JobCategory", "JobCategory")
                        .WithMany("Jobs")
                        .HasForeignKey("JobCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCategory");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Section", b =>
                {
                    b.HasOne("LMS_Data_Access_Layer.Models.Learning_Management_System.School", "school")
                        .WithMany("Sections")
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("school");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Employee", b =>
                {
                    b.HasOne("LMS_Data_Access_Layer.Models.Administration.AcademicDegree", "AcademicDegree")
                        .WithMany("Employees")
                        .HasForeignKey("AcademicDegreeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS_Data_Access_Layer.Models.Administration.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS_Data_Access_Layer.Models.Administration.Job", "Job")
                        .WithMany("Employees")
                        .HasForeignKey("JobID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS_Data_Access_Layer.Models.Administration.ReasonForLeavingWork", "ReasonForLeavingWork")
                        .WithMany("Employees")
                        .HasForeignKey("ReasonOfLeavingID");

                    b.HasOne("LMS_Data_Access_Layer.Models.Role", "Role")
                        .WithMany("Employess")
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicDegree");

                    b.Navigation("Department");

                    b.Navigation("Job");

                    b.Navigation("ReasonForLeavingWork");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.AcademicYear", b =>
                {
                    b.HasOne("LMS_Data_Access_Layer.Models.Learning_Management_System.School", "School")
                        .WithMany("AcademicYears")
                        .HasForeignKey("schoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.Classroom", b =>
                {
                    b.HasOne("LMS_Data_Access_Layer.Models.Learning_Management_System.AcademicYear", "AcademicYear")
                        .WithMany("Classrooms")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS_Data_Access_Layer.Models.Administration.Floor", "Floor")
                        .WithMany("Classrooms")
                        .HasForeignKey("FloorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_Data_Access_Layer.Models.Administration.Grade", "Grade")
                        .WithMany("Classrooms")
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Floor");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.Semester", b =>
                {
                    b.HasOne("LMS_Data_Access_Layer.Models.Learning_Management_System.AcademicYear", "AcademicYear")
                        .WithMany("Semesters")
                        .HasForeignKey("AcademicYearID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.Student", b =>
                {
                    b.HasOne("LMS_Data_Access_Layer.Models.Learning_Management_System.School", null)
                        .WithMany("Students")
                        .HasForeignKey("SchoolID");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.Subject", b =>
                {
                    b.HasOne("LMS_Data_Access_Layer.Models.Administration.Grade", "Grade")
                        .WithMany("Subjects")
                        .HasForeignKey("GradeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS_Data_Access_Layer.Models.Learning_Management_System.SubjectCategory", "SubjectCategory")
                        .WithMany("Subjects")
                        .HasForeignKey("SubjectCategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("SubjectCategory");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.AcademicDegree", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Building", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Floor", b =>
                {
                    b.Navigation("Classrooms");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Grade", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Job", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.JobCategory", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.ReasonForLeavingWork", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Administration.Section", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.AcademicYear", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("Semesters");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.School", b =>
                {
                    b.Navigation("AcademicYears");

                    b.Navigation("Buildings");

                    b.Navigation("Sections");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Learning_Management_System.SubjectCategory", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("LMS_Data_Access_Layer.Models.Role", b =>
                {
                    b.Navigation("Employess");
                });
#pragma warning restore 612, 618
        }
    }
}
